# Generated by Django 2.2.5 on 2019-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('lfno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('program', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('roomno', models.IntegerField()),
                ('hno', models.IntegerField()),
            ],
        ),
    ]
