# Generated by Django 2.2.5 on 2019-11-05 14:33

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20191105_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
