# Generated by Django 2.2.5 on 2019-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20191105_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hno', models.IntegerField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=15)),
                ('sharing', models.IntegerField()),
            ],
        ),
    ]
