# Generated by Django 2.2.5 on 2019-11-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='first.Student'),
        ),
    ]
