# Generated by Django 2.2.5 on 2019-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20191110_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
