# Generated by Django 2.2.5 on 2019-11-10 13:14

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20191110_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
